import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {emptyState,publicResults} from '../tournament.js';
test('public standings, admin standings and finals assign each bowler to exactly one category',()=>{
 const bowlers=[{gender:'Male'},{gender:'Female'},{gender:'Male Senior'},{gender:'Female Senior'},{gender:'Male Senior',superSenior:true},{gender:'Female Senior',superSenior:true},{gender:'Male',superSenior:true},{gender:'Female',superSenior:true}];
 const expected=['overall','women','seniors','seniors','superSeniors','superSeniors','superSeniors','superSeniors'];
 for(const file of ['public/app.js','private/admin.html.txt']){const source=fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),fn=source.match(/function individualDivision\(b\)\{[^\n]+/)[0],c={};vm.createContext(c);vm.runInContext(fn,c);assert.deepEqual(bowlers.map(b=>c.individualDivision(b)),expected);}
 const c={state:{teams:[{id:'T',bowlers}]},currentLang:'es',tDict:{},window:{addEventListener(){}},document:{getElementById:()=>null},calculatePlayerStandings:()=>bowlers.map((b,i)=>({...b,id:'T|'+i,teamId:'T',bowlerIndex:i,netPinfall:1000-i}))};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../private/finals.js.txt',import.meta.url),'utf8'),c);
 const seen=[];for(const type of ['overall','women','seniors','superSeniors'])for(const p of c.finalIndividuals(type)){assert.equal(expected[Number(p.key.split('|')[1])],type);seen.push(p.key);}assert.equal(seen.length,8);assert.equal(new Set(seen).size,8);
});
test('legacy overlapping individual finals are hidden pending regeneration; team finals remain',()=>{const s=emptyState();s.finals={events:{overall:{champion:{name:'Legacy duplicate'}},team:{rulesVersion:3,seeded:[],field:[]}}};const p=publicResults(s);assert.equal(p.finals.overall.categoryReviewRequired,true);assert(!JSON.stringify(p).includes('Legacy duplicate'));assert(p.finals.team);});
