import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../server.js';
import {emptyState,publicResults,validateState} from '../tournament.js';
export function fixture(){const s=emptyState();s.teams=Array.from({length:2},(_,i)=>({id:'T'+i,name:'Team '+i,shift:i+1,contact:'PRIVATE CONTACT',bowlers:Array.from({length:3},(_,j)=>({name:'Bowler '+i+j,gender:'Male',average:190,handicap:20}))}));s.calcutta={sales:{T0:{buyer:'PRIVATE BUYER',cost:100,paid:20,group:'team'}},purses:{}};return s;}
export function mock(){let row={state:fixture(),revision:0,updated_at:null},member=true,rate=true;const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'secret-test',SUPABASE_PUBLISHABLE_KEY:'public-test',ADMIN_EMAIL:'monsterproshop@outlook.com',TOURNAMENT_ID:'test',ASSETS:{fetch:async()=>new Response('PUBLIC')}};const fetcher=async(url,opts)=>{const p=new URL(url).pathname;let value;if(p.endsWith('/tournament_auth_attempt'))value=rate;else if(p==='/auth/v1/token'||p==='/auth/v1/verify'){const b=JSON.parse(opts.body);if(b.password!=='testing-only'&&b.token!=='123456')return Response.json({}, {status:400});value={access_token:'valid-token',expires_in:3600};}else if(p==='/auth/v1/user'){if(opts.headers.Authorization!=='Bearer valid-token')return Response.json({}, {status:401});value={id:'uuid',email:env.ADMIN_EMAIL,email_confirmed_at:'2026-01-01'};}else if(p.endsWith('/tournament_admins'))value=member?[{user_id:'uuid'}]:[];else if(p.endsWith('/tournament_data'))value=[row];else if(p.endsWith('/save_tournament_state')){const b=JSON.parse(opts.body);if(b.p_expected_revision!==row.revision)value={conflict:true};else{row={state:b.p_state,revision:row.revision+1};value={revision:row.revision};}}else value={};return Response.json(value);};return {env,fetcher,handler:createHandler({adminHTML:'PRIVATE ADMIN',adminFinals:'PRIVATE JS',adminStyle:'PRIVATE CSS'},fetcher),setMember:v=>member=v,setRate:v=>rate=v};}
function req(path,{body,cookie,origin='https://app.test'}={}){return new Request('https://app.test'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:'__Host-dlr_session='+cookie}:{})},body:body?JSON.stringify(body):undefined});}
test('anonymous results redact contact, buyers, debts and original state',async()=>{const m=mock(),r=await m.handler(req('/api/results'),m.env),text=await r.text();assert.equal(r.status,200);assert(!text.includes('PRIVATE'));assert(!text.includes('buyer'));assert(!text.includes('paid'));assert(!text.includes('contact'));assert.equal(JSON.parse(text).standings.teams.length,2);});
test('all private routes and backend sources fail closed',async()=>{const m=mock();for(const path of ['/api/admin/state','/admin/finals.js','/admin/finals.css'])assert.equal((await m.handler(req(path),m.env)).status,401);assert.equal((await m.handler(req('/admin/'),m.env)).status,302);for(const path of ['/server.js','/private/admin.html.txt','/supabase/01-secure-migration.sql','/backup.json'])assert.equal((await m.handler(req(path),m.env)).status,404);});
test('login checks password and issues HttpOnly secure cookie',async()=>{const m=mock();assert.equal((await m.handler(req('/api/auth/password',{body:{email:m.env.ADMIN_EMAIL,password:'wrong'}}),m.env)).status,401);const r=await m.handler(req('/api/auth/password',{body:{email:m.env.ADMIN_EMAIL,password:'testing-only'}}),m.env);assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);assert.equal((await m.handler(req('/admin/',{cookie:'valid-token'}),m.env)).status,200);});
test('email alone is insufficient: membership and valid session required',async()=>{const m=mock();m.setMember(false);assert.equal((await m.handler(req('/api/admin/state',{cookie:'valid-token'}),m.env)).status,403);assert.equal((await m.handler(req('/api/admin/state',{cookie:'expired'}),m.env)).status,401);});
test('cross-origin writes rejected, successful save increments revision, stale save conflicts',async()=>{const m=mock(),body={state:fixture(),revision:0};assert.equal((await m.handler(req('/api/admin/state',{body,cookie:'valid-token',origin:'https://evil.test'}),m.env)).status,403);assert.equal((await m.handler(req('/api/admin/state',{body,cookie:'valid-token'}),m.env)).status,200);assert.equal((await m.handler(req('/api/admin/state',{body,cookie:'valid-token'}),m.env)).status,409);});
test('rate limit and missing configuration fail closed',async()=>{const m=mock();m.setRate(false);assert.equal((await m.handler(req('/api/auth/code',{body:{email:m.env.ADMIN_EMAIL}}),m.env)).status,429);delete m.env.SUPABASE_SERVICE_ROLE_KEY;assert.equal((await m.handler(req('/api/results'),m.env)).status,503);});
test('validation rejects bad handicap and Calcutta allocations',()=>{const s=fixture();validateState(s);s.teams[0].bowlers[0].handicap=99;assert.throws(()=>validateState(s));s.teams[0].bowlers[0].handicap=20;s.calcutta.purses.team={rate:100,places:[60,60]};assert.throws(()=>validateState(s));});
test('standings computed from scores, finals whitelist excludes private metadata',()=>{const s=fixture();s.games=[{number:1,matches:[{id:'M1',aId:'T0',bId:'T1',completed:true,bowlers:[0,1,2].map(pos=>({pos,a:200,b:180})),teamScoreA:0,teamScoreB:0}]}];validateState(s);s.finals={events:{overall:{stage:'qualification',pool:[{name:'Bowler',key:'T0|0',private:'PRIVATE'}],source:'PRIVATE'}}};const p=publicResults(s);assert.equal(p.standings.teams[0].points,10);assert.equal(p.standings.players[0].netPinfall,220);assert(!JSON.stringify(p).includes('PRIVATE'));});
