import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../private/admin.html.txt',import.meta.url),'utf8');const source=html.slice(html.indexOf('function sundayShiftAssignments('),html.indexOf('\nfunction resetGames()'));
function setup(n=42,two=true){const teams=Array.from({length:n},(_,i)=>({id:'T'+i,shift:two?(i%2)+1:1}));const state={teams,games:[1,2,3,4].map(number=>({number,matches:Array.from({length:Math.ceil(n/2)},(_,i)=>({aId:'T'+(i*2),bId:i*2+1<n?'T'+(i*2+1):null,shift:1,completed:true}))})),settings:{satGames:4}};const fields={genGameSelect:{value:5},genShiftSelect:{value:1},genPoolStart:{value:1},genPoolEnd:{value:60},genTopSeedLane:{value:1},auditGameSelect:{},auditShiftFilter:{}};const alerts=[];const context={state,isAdmin:true,currentLang:'es',hasLegacyShift:()=>false,t:x=>x,document:{getElementById:id=>fields[id]},alert:s=>alerts.push(s),confirm:()=>true,calculateTeamStandings:()=>context.ranking.map(id=>({...state.teams.find(t=>t.id===id)})),randomizeTeamsForShift:ts=>ts.map(t=>t.id),buildMatchObj:(number,shift,aId,bId,laneA)=>({shift,aId,bId,laneA,laneB:laneA+1,completed:false}),save:async()=>true,activateTab:()=>{},renderGame:()=>{},ranking:teams.map(t=>t.id)};vm.createContext(context);vm.runInContext(source,context);return {context,state,fields,alerts,generate:()=>context.generateSpecificGame()};}
const pairs=(s,n,shift)=>JSON.parse(JSON.stringify(s.games.find(g=>g.number===n).matches.filter(m=>m.shift===shift).map(m=>[m.aId,m.bId])));
test('42 teams split 22 lower / 20 upper regardless of generation order',async()=>{for(const order of [[1,2],[2,1]]){const x=setup();for(const shift of order){x.fields.genShiftSelect.value=shift;await x.generate();}assert.equal(x.state.teams.filter(t=>t.shift===1).length,22);assert.equal(x.state.teams.filter(t=>t.shift===2).length,20);assert.deepEqual(pairs(x.state,5,2)[0],['T0','T1']);assert.deepEqual(pairs(x.state,5,1)[0],['T20','T21']);assert.equal(new Set(x.state.games[4].matches.flatMap(m=>[m.aId,m.bId])).size,42);}});
test('40, 44 and one-shift events retain correct group sizes',async()=>{for(const [n,two,lower,upper]of [[40,true,20,20],[44,true,22,22],[18,false,18,0]]){const x=setup(n,two);await x.generate();assert.equal(x.state.teams.filter(t=>t.shift===1).length,lower);assert.equal(x.state.teams.filter(t=>t.shift===2).length,upper);}});
test('games 6 and 7 re-pair cumulative positions without moving Sunday membership',async()=>{const x=setup(12);await x.generate();x.fields.genShiftSelect.value=2;await x.generate();const membership=x.state.teams.map(t=>t.shift);x.state.games[4].matches.forEach(m=>m.completed=true);x.context.ranking=['T2','T0','T5','T1','T4','T3','T8','T6','T11','T7','T10','T9'];x.fields.genGameSelect.value=6;await x.generate();assert.deepEqual(pairs(x.state,6,2),[['T2','T0'],['T5','T1'],['T4','T3']]);x.state.games[5].matches.forEach(m=>m.completed=true);x.context.ranking=['T3','T4','T1','T5','T0','T2','T6','T7','T8','T9','T10','T11'];x.fields.genGameSelect.value=7;await x.generate();assert.deepEqual(pairs(x.state,7,2),[['T3','T4'],['T1','T5'],['T0','T2']]);assert.deepEqual(x.state.teams.map(t=>t.shift),membership);});
test('incomplete Saturday or Sunday results and insufficient lanes never mutate data',async()=>{const x=setup();x.state.games[3].matches[0].completed=false;let before=JSON.stringify(x.state);await x.generate();assert.equal(JSON.stringify(x.state),before);x.state.games[3].matches[0].completed=true;x.fields.genPoolEnd.value=10;before=JSON.stringify(x.state);await x.generate();assert.equal(JSON.stringify(x.state),before);x.fields.genPoolEnd.value=60;await x.generate();x.fields.genGameSelect.value=6;before=JSON.stringify(x.state);await x.generate();assert.equal(JSON.stringify(x.state),before);});

